global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['prometheus-pushgateway:9091']
  - job_name: 'local8080'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      # host.docker.internal refers to host machine
      - targets: ['host.docker.internal:8080']
