{
 "title": "HTTP Client Calls - Graphite",
 "tags": [ "httpclient" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" },
   { "name": "app", "query": "APPNAME" },
   {
    "name": "env",
    "query": "prod-decaf-us-west-2, prod-decaf-us-east-1"
   },
   { "name": "instance", "query": "$app.$env.*" },
   { "name": "client", "query": "$app.$env.$instance.client.*" },
   { "name": "percentile", "query": "mean,p95,p99,p999,max" },
   { "name": "instanceB", "query": "$app.$env.*" }
  ]
 },
 "panels": [
  { "title": "Summary of all clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All service circuits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(groupByNodes({APPNAME}.$env.*.client.*.*.circuit.status, 'maxSeries', 0, 4, 7), 'max'), 0,1)"
    }
   ]
  },
  {
   "title": "All service bulkheads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative({APPNAME}.$env.*.client.*.*.bulkhead.rejected), 'maxSeries', 0, 4, 7)"
    }
   ]
  },
  {
   "title": "All service timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative({APPNAME}.$env.*.client.*.*.timeout.count), 'maxSeries', 0, 4, 6)"
    }
   ]
  },
  {
   "title": "All service failures/errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative({APPNAME}.$env.*.client.*.*.raw.{error,failure}.count), 'maxSeries', 0, 4, 6)"
    }
   ]
  },
  {
   "title": "Client statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success rate",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "target": "divideSeries(#A, #B)",
       "targetFull": "divideSeries(sumSeries($app.$env.$instance.client.$client.*.*.{success}.m1_rate), sumSeries($app.$env.$instance.client.$client.*.*.{success,error,failure}.m1_rate))"
      }
     ]
    },
    {
     "title": "Average rate per min",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "target": "sumSeries($app.$env.$instance.client.$client.*.total.{error,failure,success}.m1_rate)"
      }
     ]
    },
    {
     "title": "Max rate per min",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "target": "sumSeries($app.$env.$instance.client.$client.*.total.{error,failure,success}.m1_rate)"
      }
     ]
    },
    {
     "title": "Total max rate per min",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "target": "sumSeries($app.$env.*.client.$client.*.total.{error,failure,success}.m1_rate)"
      }
     ]
    },
    {
     "title": "$app instances",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($app.$env.*.app.version, 2)"
      }
     ]
    },
    {
     "title": "Response times comparison",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "consolidateBy(groupByNodes($app.$env.$instance.client.$client.*.raw.success.{mean,p95,p99,p999}, 'maxSeries', 2, 5, 6, 8), 'max')"
      },
      {
       "target": "consolidateBy(groupByNodes($app.$env.$instanceB.client.$client.*.raw.success.{mean,p95,p99,p999}, 'maxSeries', 2, 5, 6, 8), 'max')"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.raw.success.m1_rate, 'maxSeries', 2,5,6, 8)"
      },
      {
       "target": "groupByNodes($app.$env.$instanceB.client.$client.*.raw.success.m1_rate, 'maxSeries', 2,5,6, 8)"
      }
     ]
    },
    {
     "title": "Response times comparison per instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "consolidateBy(groupByNodes($app.$env.*.client.$client.*.raw.success.$percentile, 'maxSeries', 2, 5, 6, 8), 'max')"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response times",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.{raw,total}.success.{mean,p95,p99,p999}, 'maxSeries', 5,6, 8)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.config.{totalTimeoutInMs,peakTimeInMs}, 'maxSeries', 6)"
      }
     ]
    },
    {
     "title": "Response rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.*.{error,failure,success}.m1_rate, 'max', 5, 6, 7)"
      },
      {
       "target": "groupByNodes(scale($app.$env.$instance.client.$client.config.{averageRatePerSec,peakRatePerSec}, 60), 'maxSeries', 6)"
      }
     ]
    },
    {
     "title": "Errors and failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.{raw,total}.{success,error,failure}.count, 'maxSeries', 5, 6, 7)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.retries.*.count, 'maxSeries', 5, 6, 7)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.{circuit,bulkhead}.rejected, 'maxSeries', 5, 6, 7)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.timeout.count, 'maxSeries', 5, 6)"
      }
     ]
    },
    {
     "title": "Circuit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.circuit.status, 'maxSeries', 0, 5, 7)"
      }
     ]
    },
    {
     "title": "Circuit failure threshold",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(consolidateBy(groupByNodes($app.$env.$instance.client.$client.*.circuit.failure, 'maxSeries', 5, 7), 'max'), 0, 1)"
      },
      {
       "target": "aliasByNode(consolidateBy(groupByNodes($app.$env.$instance.client.$client.config.failureThresholdPercentage, 'maxSeries', 6), 'max'), 0)"
      }
     ]
    },
    {
     "title": "Circuit counts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(consolidateBy(groupByNodes($app.$env.$instance.client.$client.*.circuit.{buffered,maxbuffered,failed}, 'maxSeries', 5, 7), 'max'), 0, 1)"
      }
     ]
    },
    {
     "title": "Bulkhead",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.bulkhead.*, 'maxSeries', 5, 7)"
      }
     ]
    },
    {
     "title": "Http connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.http-connection-pool.*, 'maxSeries', 6)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.http-dispatcher.*, 'maxSeries', 6)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.connection-pool.*, 'sumSeries', 6)"
      },
      {
       "target": "groupByNodes($app.$env.$instance.reactor.netty.connection.provider.$client.*.connections.id.*.*.*.*.*.*.*.*, 'sumSeries', 8)"
      }
     ]
    },
    {
     "title": "Retries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.*.retries.*.m1_rate, 'maxSeries', 5, 7)"
      }
     ]
    },
    {
     "title": "Configuration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($app.$env.$instance.client.$client.config.*, 'maxSeries', 0, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Trace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP trace durations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "groupByNodes(exclude($app.$env.$instance.client.$client.http-trace.duration.*.$percentile, 'secureConnectStart'), 'maxSeries', 7)"
      },
      {
       "target": "groupByNodes(exclude($app.$env.$instance.client.$client.http-trace.*.$percentile, 'secureConnectStart'), 'maxSeries', 6)"
      }
     ]
    },
    {
     "title": "HTTP trace timings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "groupByNodes(exclude($app.$env.$instance.client.$client.http-trace.timings.*.$percentile, 'secureConnectStart'), 'maxSeries', 7)"
      }
     ]
    },
    {
     "title": "HTTP trace counts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "groupByNodes(exclude($app.$env.$instance.client.$client.http-trace.timings.*.count, 'responseHeadersStart'), 'averageSeries', 7)"
      },
      {
       "target": "groupByNodes(exclude($app.$env.$instance.client.$client.http-trace.*.count, 'responseHeadersStart'), 'averageSeries', 6)"
      }
     ]
    }
   ]
  }
 ]
}