{
 "title": "HTTP client calls - Prometheus",
 "tags": [ "httpclient" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "query": "label_values(application)" },
   {
    "name": "pod",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, pod)"
   },
   {
    "name": "client",
    "query": "label_values(http_client_requests_seconds, client)"
   },
   { "name": "percentile", "query": "0.5,0.75,0.95,0.98,0.99,0.999" },
   { "name": "window", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Summary of all clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client circuit states",
   "type": "graph",
   "description": "0 - closed, 1 - half-open, 2 - open",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (application, client) (http_client_request_circuit_status)",
     "legendFormat": "{{application}} - {{client}}"
    }
   ]
  },
  {
   "title": "Client bulkhead rejects",
   "type": "graph",
   "description": "0 - closed, 1 - half-open, 2 - open",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (application,client) (rate(http_client_request_bulkhead_rejected[$window]))",
     "legendFormat": "{{application}} - {{client}}"
    }
   ]
  },
  {
   "title": "Client timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (application,client) (rate(http_client_request_timeouts_total[$window]))",
     "legendFormat": "{{application}} - {{client}}"
    }
   ]
  },
  {
   "title": "Client request error/failure rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (application,client) (rate(http_client_requests_seconds_count{type=\"total\", status=~\"error|failure\"}[$window]))",
     "legendFormat": "{{application}} - {{client}}"
    }
   ]
  },
  { "title": "Client summary in $application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average success rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\", status=\"success\"}[$window]))\n/sum(rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\"}[$window]))"
    }
   ]
  },
  {
   "title": "Average request rate per instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "max(rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\"}[$window]))"
    }
   ]
  },
  {
   "title": "Maximum request rate per instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max(rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\"}[$window]))"
    }
   ]
  },
  {
   "title": "Maximum total request rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\"}[$window]))"
    }
   ]
  },
  {
   "title": "Client details in $application $pod instance(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful raw response times (per quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (endpoint,quantile)(http_client_requests_seconds{application=\"$application\", pod=~\"$pod\", client=\"$client\", status=\"success\", type=\"raw\"})",
       "legendFormat": "{{endpoint}} - {{quantile}}"
      },
      {
       "expr": "max (http_client_config_averageTimeInMs{application=\"$application\", pod=~\"$pod\", client=\"$client\"}/1000)",
       "legendFormat": "config - avg response time"
      },
      {
       "expr": "max (http_client_config_peakTimeInMs{application=\"$application\", pod=~\"$pod\", client=\"$client\"}/1000)",
       "legendFormat": "config - peak response time"
      }
     ]
    },
    {
     "title": "Successful request rates (per type)",
     "type": "graph",
     "description": "raw - a single http level request.\n\ntotal - a single api level request including retries (1 or more raw requests).",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint,type,status) (rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", status=\"success\"}[$window]))",
       "legendFormat": "{{endpoint}} - {{type}} - {{status}}"
      }
     ]
    },
    {
     "title": "Failed request rates (per type and status)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint,type,status) (rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", status=~\"error|failure\"}[$window]))",
       "legendFormat": "{{endpoint}} - {{type}} - {{status}}"
      }
     ]
    },
    {
     "title": "Request counts (per type and status)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint,type,status) (http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - {{type}} - {{status}}"
      }
     ]
    },
    {
     "title": "Circuit state",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (endpoint) (http_client_request_circuit_status{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Circuit failure rate",
     "type": "graph",
     "description": "failure rate threshold is the configured value for the client. ",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max by (endpoint) (http_client_request_circuit_failure{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "max (http_client_config_failureThresholdPercentage{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "failure threshold"
      }
     ]
    },
    {
     "title": "Circuit slow requests ratio",
     "type": "graph",
     "description": "slow call rate threshold is the configured value for the client. ",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max by (endpoint) (http_client_request_circuit_slowness{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}}"
      },
      {
       "expr": "max (http_client_config_slowCallRateThreshold{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "failure threshold"
      }
     ]
    },
    {
     "title": "Circuit statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_buffered{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - buffered"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_successful{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - successful"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_failed{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - failed"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_rejected{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - rejected"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_slow{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - slow"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_slow_failed{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - slow failed"
      },
      {
       "expr": "sum by (endpoint) (http_client_request_circuit_slow_successful{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{endpoint}} - slow successful"
      }
     ]
    },
    {
     "title": "Request retry rates",
     "type": "graph",
     "description": "raw - a single http level request.\n\ntotal - a single api level request including retries (1 or more raw requests).",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint,retry) (rate(http_client_request_retries_total{application=\"$application\", pod=~\"$pod\", client=\"$client\"}[$window]))",
       "legendFormat": "{{endpoint}} - {{retry}}"
      }
     ]
    },
    {
     "title": "HTTP connection statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max (http_client_dispatcher_max_calls{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "dispatcher - max"
      },
      {
       "expr": "max (http_client_dispatcher_running_calls{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "dispatcher - running "
      },
      {
       "expr": "max (http_client_dispatcher_queued_calls{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "dispatcher - queued"
      },
      {
       "expr": "max (http_client_connection_pool_total_connections{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "connection pool - total"
      },
      {
       "expr": "max (http_client_connection_pool_idle_connections{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "connection pool - idle"
      }
     ]
    },
    {
     "title": "Client configuration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (config) (http_client_configuration{application=\"$application\", pod=~\"$pod\", client=\"$client\"})",
       "legendFormat": "{{config}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client comparison in $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response times @$percentile (per instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (endpoint,pod)(http_client_requests_seconds{application=\"$application\", pod=~\"$pod\", client=\"$client\", quantile=\"$percentile\", type=\"raw\"})",
       "legendFormat": "{{endpoint}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Request rates (per instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint,pod) (rate(http_client_requests_seconds_count{application=\"$application\", pod=~\"$pod\", client=\"$client\", type=\"total\"}[$window]))",
       "legendFormat": "{{endpoint}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}